export * from './sortTagsPlugin'
export * from './titleTemplatePlugin'
export * from './deprecatedTagAttrPlugin'
export * from './provideTagHashPlugin'
export * from './eventHandlersPlugin'
export * from './dedupesTagsPlugin'
export * from './templateParamsPlugin'
export * from './capoPlugin'
