#!/usr/bin/env node
/**
 * Static site generator for the real-browser v3 vs v4 demo.
 *
 * Produces three pages in the output dir (default: $V4DEMO_OUT or
 * .out/v4demo under the system temp dir; pass --out <dir>):
 *   index-v3.html        v3 SSR head + v3 client bundle
 *   index-v4.html        v4 SSR head + v4 client bundle
 *   index-v4-sealed.html v4 SSR of the emit.ts sealed route plan + tiny
 *                        plan-native client (see src/sealed-runtime.ts)
 *
 * Head HTML is rendered at build time by the respective server renderer;
 * client bundles are esbuild --bundle --minify straight off the repo TS
 * sources. Built artifacts stay out of git.
 */
import { execSync } from 'node:child_process'
import { readdirSync, writeFileSync } from 'node:fs'
import { gzipSync } from 'node:zlib'
import { createRequire } from 'node:module'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const demoDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(demoDir, '../../..')

const outArg = process.argv.indexOf('--out')
const OUT = resolve(outArg > -1
  ? process.argv[outArg + 1]
  : process.env.V4DEMO_OUT || join(process.env.TMPDIR || '/tmp', 'v4demo'))
const GEN = join(OUT, 'gen')
const DIST = join(OUT, 'dist')

function resolveEsbuild() {
  const req = createRequire(join(repoRoot, 'packages/unhead/package.json'))
  for (const attempt of ['esbuild', null]) {
    try {
      if (attempt)
        return req(attempt)
    }
    catch {}
  }
  // pnpm store fallback: any esbuild@* in the workspace store
  const store = join(repoRoot, 'node_modules/.pnpm')
  const hits = readdirSync(store).filter(d => d.startsWith('esbuild@')).sort()
  if (!hits.length)
    throw new Error('esbuild not found; pnpm install first')
  return createRequire(import.meta.url)(join(store, hits.at(-1), 'node_modules/esbuild'))
}

const esbuild = resolveEsbuild()

async function bundle(entry, outfile, opts = {}) {
  await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    outfile,
    logLevel: 'silent',
    define: { 'process.env.NODE_ENV': '"production"' },
    ...opts,
  })
}

function pageHtml({ name, label, blurb, ssr, sizeNote }) {
  return `<!DOCTYPE html>
<html${ssr.htmlAttrs}>
<head>
${ssr.headTags}
</head>
<body${ssr.bodyAttrs}>
${ssr.bodyTagsOpen}
<main style="font-family:ui-monospace,monospace;max-width:76ch;margin:2rem auto;padding:1.5rem;color:#1a1a1a;background:#fff;border:1px solid #ddd;border-radius:8px">
  <h1 style="font-size:1.2rem">unhead real-browser demo: ${label}</h1>
  <p>${blurb}</p>
  <p>bundle: ${sizeNote}</p>
  <pre id="results" style="border:1px solid #bbb;background:#f6f6f6;padding:1rem;white-space:pre-wrap;overflow-x:auto">running…</pre>
</main>
${ssr.bodyTags}
<script type="module" src="./${name}.js"></script>
</body>
</html>
`
}

async function main() {
  await mkdir(GEN, { recursive: true })
  await mkdir(DIST, { recursive: true })

  // 1. build-time module (SSR renderers + plan emitter) and run it
  const btOut = join(GEN, 'buildtime.mjs')
  await bundle(join(demoDir, 'src/buildtime.ts'), btOut, { platform: 'node', format: 'esm' })
  const bt = await import(pathToFileURL(btOut).href)

  const sealed = bt.emitSealed()
  await writeFile(join(GEN, 'sealed-data.mjs'), [
    '// generated by build.mjs from emit.ts emitRoutePlan output',
    `export const PLAN = ${JSON.stringify(sealed.plan)}`,
    `export const FILLS_A = ${JSON.stringify(sealed.fillsA)}`,
    `export const FILLS_B = ${JSON.stringify(sealed.fillsB)}`,
    '',
  ].join('\n'))

  const ssr = {
    'v3': bt.ssrV3(),
    'v4': bt.ssrV4(),
    'v4-sealed': bt.ssrV4Sealed(sealed.plan, sealed.fillsA),
  }

  // 2. client bundles
  const clientOpts = { minify: true, format: 'esm', platform: 'browser', target: ['chrome110'] }
  await bundle(join(demoDir, 'src/client-v3.ts'), join(DIST, 'v3.js'), clientOpts)
  await bundle(join(demoDir, 'src/client-v4.ts'), join(DIST, 'v4.js'), clientOpts)
  await bundle(join(demoDir, 'src/client-v4-sealed.ts'), join(DIST, 'v4-sealed.js'), {
    ...clientOpts,
    alias: { '#sealed-data': join(GEN, 'sealed-data.mjs') },
  })

  const sizes = {}
  for (const name of ['v3', 'v4', 'v4-sealed']) {
    const buf = await readFile(join(DIST, `${name}.js`))
    sizes[name] = { raw: buf.length, gzip: gzipSync(buf, { level: 9 }).length }
  }

  // 3. pages
  const blurbs = {
    'v3': 'SSR head by v3 server renderer; hydrated by the v3 client (sync render per push/patch).',
    'v4': 'SSR head by v4 server renderer; hydrated by the v4 client (batched, flushed sync via injectable scheduler).',
    'v4-sealed': 'SSR head from the emit.ts sealed route plan; client is the real sealed profile (attachDom + installPlanRenderer, no L1 compiler).',
  }
  for (const name of Object.keys(ssr)) {
    const s = sizes[name]
    writeFileSync(join(DIST, `index-${name}.html`), pageHtml({
      name,
      label: name,
      blurb: blurbs[name],
      ssr: ssr[name],
      sizeNote: `${s.raw} B raw, ${s.gzip} B gzip`,
    }))
  }
  writeFileSync(join(DIST, 'sizes.json'), JSON.stringify(sizes, null, 2))

  // 4. stub assets so the SSR-referenced urls do not 404-spam the console
  await mkdir(join(DIST, '_nuxt'), { recursive: true })
  for (const f of ['entry.css', 'page.css', 'page2.css', 'page3.css', 'page4.css'])
    writeFileSync(join(DIST, f), '')
  for (const f of ['runtime.js', 'vendors.js', 'app.js', 'module.js', 'legacy.js'])
    writeFileSync(join(DIST, `_nuxt/${f}`), '')
  writeFileSync(join(DIST, 'payload.json'), '{}')

  console.log(`built -> ${DIST}`)
  console.log(JSON.stringify(sizes, null, 2))
  try {
    console.log(`git rev: ${execSync('git rev-parse --short HEAD', { cwd: repoRoot }).toString().trim()}`)
  }
  catch {}
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
