export const URL_META_KEYS = /* @__PURE__ */ new Set([
  'og:url',
  'og:image',
  'og:image:url',
  'og:image:secure_url',
  'og:video',
  'og:video:url',
  'og:video:secure_url',
  'og:audio',
  'og:audio:url',
  'og:audio:secure_url',
  'twitter:image',
  'twitter:image:src',
  'twitter:player',
  'twitter:player:stream',
])

export const KNOWN_META_PROPERTIES = /* @__PURE__ */ new Set([
  'article:author',
  'article:expiration_time',
  'article:modified_time',
  'article:published_time',
  'article:section',
  'article:tag',
  'book:author',
  'book:isbn',
  'book:release_date',
  'book:tag',
  'fb:app_id',
  'og:audio',
  'og:audio:secure_url',
  'og:audio:type',
  'og:audio:url',
  'og:description',
  'og:determiner',
  'og:image',
  'og:image:height',
  'og:image:secure_url',
  'og:image:type',
  'og:image:url',
  'og:image:width',
  'og:locale',
  'og:locale:alternate',
  'og:site_name',
  'og:title',
  'og:type',
  'og:url',
  'og:video',
  'og:video:height',
  'og:video:secure_url',
  'og:video:type',
  'og:video:url',
  'og:video:width',
  'profile:first_name',
  'profile:gender',
  'profile:last_name',
  'profile:username',
])

export const KNOWN_META_NAMES = /* @__PURE__ */ new Set([
  'apple-itunes-app',
  'apple-mobile-web-app-capable',
  'apple-mobile-web-app-status-bar-style',
  'apple-mobile-web-app-title',
  'application-name',
  'author',
  'color-scheme',
  'creator',
  'description',
  'fb:app_id',
  'fediverse:creator',
  'format-detection',
  'generator',
  'google-site-verification',
  'google',
  'googlebot',
  'keywords',
  'mobile-web-app-capable',
  'msapplication-Config',
  'msapplication-TileColor',
  'msapplication-TileImage',
  'publisher',
  'rating',
  'referrer',
  'robots',
  'theme-color',
  'viewport',
  'twitter:app:id:googleplay',
  'twitter:app:id:ipad',
  'twitter:app:id:iphone',
  'twitter:app:name:googleplay',
  'twitter:app:name:ipad',
  'twitter:app:name:iphone',
  'twitter:app:url:googleplay',
  'twitter:app:url:ipad',
  'twitter:app:url:iphone',
  'twitter:card',
  'twitter:creator',
  'twitter:creator:id',
  'twitter:data:1',
  'twitter:data:2',
  'twitter:description',
  'twitter:image',
  'twitter:image:alt',
  'twitter:label:1',
  'twitter:label:2',
  'twitter:player',
  'twitter:player:height',
  'twitter:player:stream',
  'twitter:player:width',
  'twitter:site',
  'twitter:site:id',
  'twitter:title',
])

export const TAG_PRIORITY_ALIASES = ['critical', 'high', 'low'] as const
export type TagPriorityAlias = typeof TAG_PRIORITY_ALIASES[number]

/**
 * Deprecated v2 tag-prop names with their v3 replacement, used by both the
 * runtime validate plugin and the eslint plugin.
 */
export const DEPRECATED_PROPS: Record<string, { replacement: string, ruleId: 'deprecated-prop-children' | 'deprecated-prop-hid-vmid' | 'deprecated-prop-body' }> = {
  children: { replacement: 'innerHTML', ruleId: 'deprecated-prop-children' },
  hid: { replacement: 'key', ruleId: 'deprecated-prop-hid-vmid' },
  vmid: { replacement: 'key', ruleId: 'deprecated-prop-hid-vmid' },
  body: { replacement: 'tagPosition: \'bodyClose\'', ruleId: 'deprecated-prop-body' },
}
