export const schemaAutoImports = [
  'defineAddress',
  'defineAggregateOffer',
  'defineAggregateRating',
  'defineArticle',
  'defineBook',
  'defineBookEdition',
  'defineBreadcrumb',
  'defineComment',
  'defineCourse',
  'defineEvent',
  'defineFoodEstablishment',
  'defineHowTo',
  'defineHowToStep',
  'defineImage',
  'defineItemList',
  'defineJobPosting',
  'defineListItem',
  'defineLocalBusiness',
  'defineMovie',
  'defineOffer',
  'defineOpeningHours',
  'defineOrganization',
  'definePerson',
  'definePlace',
  'defineProduct',
  'defineQuestion',
  'defineReadAction',
  'defineRecipe',
  'defineReview',
  'defineSearchAction',
  'defineSoftwareApp',
  'defineVideo',
  'defineVirtualLocation',
  'defineWebPage',
  'defineWebSite',
  'useSchemaOrg',
]

export const schemaOrgAutoImports = [
  {
    from: '@unhead/schema-org/svelte',
    imports: schemaAutoImports,
  },
]
