import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  clean: true,
  declaration: true,
  externals: [
    'react',
    'vite',
    'webpack',
    '@rspack/core',
    'rollup',
    'unplugin',
    'magic-string',
    'oxc-walker',
    '@unhead/bundler',
    '@unhead/bundler/vite',
    '@unhead/bundler/webpack',
    '@unhead/bundler/rspack',
    '@unhead/bundler/rollup',
  ],
  rollup: {
    inlineDependencies: true,
    emitCJS: false,
  },
  entries: [
    { input: 'src/index', name: 'index' },
    { input: 'src/server', name: 'server' },
    { input: 'src/client', name: 'client' },
    { input: 'src/stream/server', name: 'stream/server' },
    { input: 'src/stream/client', name: 'stream/client' },
    { input: 'src/utils', name: 'utils' },
    { input: 'src/plugins', name: 'plugins' },
    { input: 'src/vite', name: 'vite' },
    { input: 'src/webpack', name: 'webpack' },
    { input: 'src/rspack', name: 'rspack' },
    { input: 'src/rollup', name: 'rollup' },
    { input: 'src/stream/vite', name: 'stream/vite' },
    { input: 'src/helmet', name: 'helmet' },
  ],
})
