/**
 * v4 sealed page: the compiled-app story. The whole route head was pre-merged
 * at build time by emit.ts (emitRoutePlan) into one sealed plan whose only
 * dynamic values are 6 fill holes (title, description, canonical, og:title,
 * og:description, og:url). The client ships no compiler, no dedupe, no
 * resolver; hydration adopts the hole-bearing SSR elements and navigation is
 * patch(plan, newFills).
 *
 * `#sealed-data` is generated by build.mjs from the real emit.ts output.
 */
// @ts-expect-error generated at build time, aliased by esbuild
import { FILLS_A, FILLS_B, PLAN } from '#sealed-data'
import { run } from './runner'
import { createSealedHead } from './sealed-runtime'

run({
  label: 'v4-sealed',
  hydrate() {
    const head = createSealedHead(PLAN, FILLS_A)
    return toB => head.patch(toB ? FILLS_B : FILLS_A)
  },
})
