/**
 * v4 sealed page: the compiled-app story on shipped code. The whole route
 * head is pre-merged at build time by emit.ts (emitRoutePlan) into one sealed
 * plan whose only dynamic values are 6 fill holes (title, description,
 * canonical, og:title, og:description, og:url). The client is the real
 * sealed profile: attachDom over a compile-less core plus the opt-in plan
 * renderer from client-plans.ts; no L1 compiler ships. Navigation is
 * patch(plan, newFills).
 *
 * `#sealed-data` is generated by build.mjs from the real emit.ts output.
 */
// @ts-expect-error generated at build time, aliased by esbuild
import { FILLS_A, FILLS_B, PLAN } from '#sealed-data'
import { attachDom } from '../../../../packages/unhead/src/v4/client'
import { installPlanRenderer } from '../../../../packages/unhead/src/v4/client-plans'
import { createCore } from '../../../../packages/unhead/src/v4/core'
import { run } from './runner'

run({
  label: 'v4-sealed',
  hydrate() {
    const head = attachDom(createCore({ ssr: false }), { scheduler: () => {} })
    installPlanRenderer(head)
    const entry = head.push(PLAN, { fills: FILLS_A })
    head.render()
    return (toB) => {
      entry.patch(PLAN, toB ? FILLS_B : FILLS_A)
      head.render()
    }
  },
})
