name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
      - v2
    paths-ignore:
      - '**/README.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm i
      - run: pnpm lint

  typecheck:
    runs-on: ubuntu-24.04-arm
    env:
      NODE_OPTIONS: --max-old-space-size=8048
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm i
      - run: pnpm build
      - run: pnpm typecheck
      - run: pnpm test:attw

  test:
    runs-on: ubuntu-24.04-arm
    env:
      NODE_OPTIONS: --max-old-space-size=8048
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm i
      - run: pnpm build
      - run: pnpm exec vitest run
