name: Test

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Use Node.js 22.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm i

      - name: Build
        run: pnpm run build
        env:
          NODE_OPTIONS: --max-old-space-size=8048

      - name: Typecheck
        run: pnpm typecheck && pnpm test:attw
        env:
          NODE_OPTIONS: --max-old-space-size=8048

      - name: Test
        run: pnpm run test
        env:
          NODE_OPTIONS: --max-old-space-size=8048
