name: Update Bundle Stats

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install pnpm
        uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1

      - name: Use Node.js 24.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Run bundle size test
        run: pnpm test:bundle-size

      - name: Run Vue bundle size test
        run: pnpm test:vue-bundle-size

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - name: Update stats
        run: bun bench/bundle/update.ts

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add bench/bundle/last.json
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update bundle stats [skip ci]"
          git push
