import {
  addressResolver,
  aggregateOfferResolver,
  aggregateRatingResolver,
  articleResolver,
  bookEditionResolver,
  bookResolver,
  breadcrumbResolver,
  commentResolver,
  courseResolver,
  eventResolver,
  foodEstablishmentResolver,
  howToResolver,
  howToStepResolver,
  imageResolver,
  itemListResolver,
  jobPostingResolver,
  listItemResolver,
  localBusinessResolver,
  movieResolver,
  offerResolver,
  openingHoursResolver,
  organizationResolver,
  personResolver,
  placeResolver,
  productResolver,
  questionResolver,
  readActionResolver,
  recipeResolver,
  reviewResolver,
  searchActionResolver,
  softwareAppResolver,
  videoResolver,
  virtualLocationResolver,
  webPageResolver,
  webSiteResolver,
} from './nodes'

export const SchemaOrgNodeResolverMap = {
  address: addressResolver,
  aggregateOffer: aggregateOfferResolver,
  aggregateRating: aggregateRatingResolver,
  article: articleResolver,
  breadcrumb: breadcrumbResolver,
  comment: commentResolver,
  event: eventResolver,
  foodEstablishment: foodEstablishmentResolver,
  virtualLocation: virtualLocationResolver,
  place: placeResolver,
  howTo: howToResolver,
  howToStep: howToStepResolver,
  image: imageResolver,
  localBusiness: localBusinessResolver,
  offer: offerResolver,
  openingHours: openingHoursResolver,
  organization: organizationResolver,
  person: personResolver,
  product: productResolver,
  question: questionResolver,
  recipe: recipeResolver,
  review: reviewResolver,
  video: videoResolver,
  webPage: webPageResolver,
  webSite: webSiteResolver,
  book: bookResolver,
  course: courseResolver,
  itemList: itemListResolver,
  jobPosting: jobPostingResolver,
  listItem: listItemResolver,
  movie: movieResolver,
  searchAction: searchActionResolver,
  readAction: readActionResolver,
  softwareApp: softwareAppResolver,
  bookEdition: bookEditionResolver,
} as const
